version: '2.2'
services: 
  config:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: config-server
    ports:
      - "8888:8888"
    networks:
      - network1
    environment:
     - "SPRING_PROFILES_ACTIVE=native"
  discovery:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    image: discovery-server
    ports:
      - "9091:9091"
    networks:
      - network1
    depends_on:
      - config
    environment:
     - "SPRING_PROFILES_ACTIVE=int" 
  api:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    image: api-server
    depends_on:
     - discovery
     - config
    ports:
     - "9090:9090"
    environment:
     - "SPRING_PROFILES_ACTIVE=int" 
    networks:
     - network1
  city:
    build:
      context: ./city-server
      dockerfile: Dockerfile
    image: city-server
    ports:
      - 8080
    environment:
     - "SPRING_PROFILES_ACTIVE=int" 
    networks:
      - network1
    scale: 1
    depends_on:
      - discovery
      - config
  calculation:
    build:
      context: ./calculation-server
      dockerfile: Dockerfile
    image: calculation-server
    ports:
      - 8090
    environment:
     - "SPRING_PROFILES_ACTIVE=int" 
    networks:
      - network1
    scale: 1
    depends_on:
      - discovery
      - config 
      - city
networks:
  network1: